### ISSUE TITLE
Visualize the GT Voxel

### ISSUE THREAD

**Issue by Victor-Xiaoyu-Ye** [nv-tlabs/SCube#5]
Hi, appreciate the excellent work.

I've downloaded the GT voxel, how should i visualize, since it is a .pth and don’t have vix_ijk keys.

thansk.

**Comment by yifanlu0227** [comment]
Hi, we have added a script for GT voxel visualization. You can run the following command:
```bash
python inference/visualize_gt_pc.py -p <GT_VOXEL_TAR_FILE>
```
where `<GT_VOXEL_TAR_FILE>` should be tar file under `pc_voxelsize_01` folder.

You can `poetry install` again and use the shortcut:
```bash
vis-gt-pc -p <GT_VOXEL_TAR_FILE>
```
<img width="986" alt="Screenshot 2024-12-27 at 20 02 41" src="https://github.com/user-attachments/assets/d963d389-228d-4eed-8568-318ac0e5d27f" />

**Comment by Victor-Xiaoyu-Ye** [comment]
Very appreciate the constructive response!
